---
- name: Collect exam files from Windows computers
  hosts: windows
  gather_facts: false

  tasks:
    - name: Close Foxit PDF Reader
      ansible.windows.win_shell: |
        Get-Process FoxitPDFReader -ErrorAction SilentlyContinue | Stop-Process

    - name: Find directories directly under D drive
      ansible.windows.win_find:
        paths: 'D:\'
        file_type: directory
        recurse: false
      register: all_dirs

    - name: Filter student exam directories
      ansible.builtin.set_fact:
        exam_dirs: >-
          {{
            all_dirs.files
            | selectattr('filename', 'search', '[0-9]{9}$')
            | list
          }}

    - name: Show matched exam directories
      ansible.builtin.debug:
        msg: "Exam directory found: {{ item.path }}"
      loop: "{{ exam_dirs }}"

    - name: Find files inside exam directories
      ansible.windows.win_find:
        paths: "{{ item.path }}"
        file_type: file
        recurse: true
      loop: "{{ exam_dirs }}"
      register: student_exam_files

    - name: Collect exam files
      ansible.builtin.fetch:
        src: "{{ item.1.path }}"
        dest: "/home/rafi/exam-collector/collected/{{ inventory_hostname }}/{{ item.0.item.filename }}/"
        flat: true
      loop: "{{ student_exam_files.results | subelements('files') }}"
